### ISSUE TITLE
Baidu link not usable in Canada

### ISSUE THREAD

**Issue by jyotiConeLabs** [isbrycee/GEM-Glass-Segmentor#1]
Hi there, 

This is some great work with impressive results. I want to check the results on some custom data.

I'm trying to download the checkpoints but baidu links are unusable if you dont have a baidu account. I don't have a chinese number so i cannot create a baidu account. 

I'm not sure if you have access to google drive or one drive, but if you do can you upload the checkpoints there?

Any help will be very much appreciated.

**Comment by isjinghao** [comment]
I am sorry for late reply. Maybe I can share the checkpoints to you via email. Could you leave your email and the checkpoints you want to get here?

I will share to you once I get your connection.

**Comment by isjinghao** [comment]
All pre-trained models can also download from Huggingface: https://huggingface.co/Bryceee/GEM-Glass-Segment-model/tree/main
